In [3]:
#Ödev-1:
#Bir sözlük oluşturulur ve bu sözlükte öğrencilerin isimleri ve Matematik, Fizik, Kimya notları tutulur. Kullanıcıdan isim ve ders ismi(Matematik, Fizik, Kimya) istenir ve bu bilgilere göre çıktı verilir.

#Sözlük üzerinde değerleri değiştirme, yeni değer ekleme, kullanıcıya ulaşmak istediği bilgileri sorma gibi uygulamalar yapın.


StudentNotes = {
    "Zeliha": {"Matematik": 100, "Fizik": 100, "Kimya": 95},
    "Melisa": {"Matematik": 75, "Fizik": 55, "Kimya": 100},
    "Umut": {"Matematik": 65, "Fizik": 50, "Kimya": 80}
}

isim = input("Öğrencinin ismini giriniz: ")
dersAdi = input("Ders ismini giriniz(Matematik, Fizik, Kimya): ")

if isim in StudentNotes:
    if dersAdi in StudentNotes[isim]:
        print(f"{isim}'in {dersAdi} notu: {StudentNotes[isim][dersAdi]}")
    else:
        print(f"{isim} isimli öğrencinin {dersAdi} notu bulunamadı.")
else:
    print(f"{isim} isimli öğrenci bulunamadı.")


#Değerleri değiştirme 
isim = input("Notunu güncellemek istediğiniz öğrencinin ismini girin: ")
ders = input("Notunu güncellemek istediğiniz ders ismini girin (Matematik, Fizik, Kimya): ")
yeni_not = int(input(f"{isim}'in {ders} için yeni notunu girin: "))

#Öğrencinin ders notunu güncelle
if isim in StudentNotes:
    if ders in StudentNotes[isim]:
        StudentNotes[isim][ders] = yeni_not
        print(f"{isim}'in {ders} notu güncellendi: {StudentNotes[isim][ders]}")
    else:
        print(f"{isim} isimli öğrencinin {ders} dersi bulunamadı.")
else:
    print(f"{isim} isimli öğrenci bulunamadı.")

#Yeni öğrenci eklemek için isim ve not bilgilerini alalım
isim = input("Yeni öğrencinin ismini girin: ")
matematik_notu = int(input(f"{isim}'in Matematik notunu girin: "))
fizik_notu = int(input(f"{isim}'in Fizik notunu girin: "))
kimya_notu = int(input(f"{isim}'in Kimya notunu girin: "))

#Yeni öğrenciyi sözlüğe ekleme
StudentNotes[isim] = {
    "Matematik": matematik_notu,
    "Fizik": fizik_notu,
    "Kimya": kimya_notu
}
print(f"{isim} isimli öğrenci başarıyla eklendi.")


#Tüm öğrencilerin notlarını yazdırma
for ogrenci, notlar in StudentNotes.items():
    print(f"{ogrenci}:")
    for ders, notu in notlar.items():
        print(f"  {ders}: {notu}")

Öğrencinin ismini giriniz:  umur
Ders ismini giriniz(Matematik, Fizik, Kimya):  kimya


umur isimli öğrenci bulunamadı.


Notunu güncellemek istediğiniz öğrencinin ismini girin:  umut
Notunu güncellemek istediğiniz ders ismini girin (Matematik, Fizik, Kimya):  matematik
umut'in matematik için yeni notunu girin:  67


umut isimli öğrenci bulunamadı.


Yeni öğrencinin ismini girin:  Melisa
Melisa'in Matematik notunu girin:  98
Melisa'in Fizik notunu girin:  76
Melisa'in Kimya notunu girin:  95


Melisa isimli öğrenci başarıyla eklendi.
Merve:
  Matematik: 100
  Fizik: 100
  Kimya: 95
Melike:
  Matematik: 75
  Fizik: 55
  Kimya: 100
Murat:
  Matematik: 65
  Fizik: 50
  Kimya: 80
Melisa:
  Matematik: 98
  Fizik: 76
  Kimya: 95


In [5]:
 #Ödev-1: 
 #1.Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. 

 #Ödev-2:
 #2.İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. 

 #Ödev-3:
 #3.Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

 #Ödev-4: 
 #4.Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir. 


import numpy as np

#1.örnek
array_1d = np.array([1, 2, 3, 4, 5], dtype=int)
print("Bir boyutlu array:", array_1d)
print("Array'in boyutu:", array_1d.ndim)
print("Array'in eleman sayısı:", array_1d.size)
print("Array'in şekli:", array_1d.shape)

#2.örnek
array_2d = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print("\nİki boyutlu array:")
print(array_2d)
print("Array'in boyutu:", array_2d.ndim)
print("Array'in eleman sayısı:", array_2d.size)
print("Array'in şekli:", array_2d.shape)  
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=int)
print("\nÜç boyutlu array:")
print(array_3d)
print("Array'in boyutu:", array_3d.ndim)
print("Array'in eleman sayısı:", array_3d.size)
print("Array'in şekli:", array_3d.shape)  

#3.örnek
print("\nİki boyutlu array üzerinde indexleme:")
print("array_2d[0, 1] =", array_2d[0, 1]) 
print("\nÜç boyutlu array üzerinde indexleme:")
print("array_3d[1, 0, 2] =", array_3d[1, 0, 2]) 
print("\nİki boyutlu array üzerinde dilimleme:")
print("array_2d[:, 1:] =\n", array_2d[:, 1:])  
print("\nÜç boyutlu array üzerinde dilimleme:")
print("array_3d[1, :, :2] =\n", array_3d[1, :, :2]) 

#4.örnek
zeros_array = np.zeros((2, 3), dtype=int)
print("\nSıfırlardan oluşan array:")
print(zeros_array)
ones_array = np.ones((2, 3), dtype=int)
print("\nBirlerden oluşan array:")
print(ones_array)
combined_v = np.vstack((zeros_array, ones_array))
print("\nSatır bazında birleştirilmiş array (vstack):")
print(combined_v)
combined_h = np.hstack((zeros_array, ones_array))
print("\nSütun bazında birleştirilmiş array (hstack):")
print(combined_h)


Bir boyutlu array: [1 2 3 4 5]
Array'in boyutu: 1
Array'in eleman sayısı: 5
Array'in şekli: (5,)

İki boyutlu array:
[[1 2 3]
 [4 5 6]]
Array'in boyutu: 2
Array'in eleman sayısı: 6
Array'in şekli: (2, 3)

Üç boyutlu array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Array'in boyutu: 3
Array'in eleman sayısı: 12
Array'in şekli: (2, 2, 3)

İki boyutlu array üzerinde indexleme:
array_2d[0, 1] = 2

Üç boyutlu array üzerinde indexleme:
array_3d[1, 0, 2] = 9

İki boyutlu array üzerinde dilimleme:
array_2d[:, 1:] =
 [[2 3]
 [5 6]]

Üç boyutlu array üzerinde dilimleme:
array_3d[1, :, :2] =
 [[ 7  8]
 [10 11]]

Sıfırlardan oluşan array:
[[0 0 0]
 [0 0 0]]

Birlerden oluşan array:
[[1 1 1]
 [1 1 1]]

Satır bazında birleştirilmiş array (vstack):
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]

Sütun bazında birleştirilmiş array (hstack):
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
